wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.11
    framework: huggingface
    huggingface_version: 4.18.0
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.12
    start_time: 1650376639
    t:
      1:
      - 1
      - 3
      - 5
      - 11
      - 49
      2:
      - 1
      - 3
      - 5
      - 11
      - 49
      3:
      - 2
      4: 3.8.12
      5: 0.12.11
      6: 4.18.0
      8:
      - 1
      - 5
learning_rate:
  desc: null
  value: 3.0e-05
